version: "3.1"
services:

    php:
        build:
            context: .
            args:
                - WITH_XDEBUG=true
        container_name: ${PROJECT_NAME:-api}-php
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html:rw
            - ./.docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        ports:
            - "9010:9000"
        tty: true
        env_file: .env

    nginx:
        image: nginx:alpine
        container_name: ${PROJECT_NAME:-api}-nginx
        working_dir: /var/www/html
        depends_on:
            - php
        volumes:
            - .:/var/www/html:rw
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/mysql/data
        ports:
            - "80:80"
            - "443:443"

    mysql:
        image: mysql:8.0
        container_name: ${PROJECT_NAME:-api}-mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        working_dir: /mysql/data
        volumes:
            - .:/var/www/html
        environment:
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"


#volumes:
###> doctrine/doctrine-bundle ###
#  db-data:
###< doctrine/doctrine-bundle ###
